[project]
name = "checkit-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "ipykernel>=7.2.0",
    "kagglehub>=1.0.0",
    "pandas>=3.0.1",
    "pydantic>=2.12.5",
    "selenium>=4.41.0",
    "setuptools>=82.0.0",
    "undetected-chromedriver>=3.5.5",
]
